ALTER TABLE words
ADD COLUMN IF NOT EXISTS meaning_2 TEXT;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS daily_earned_tokens INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_earn_date DATE,
ADD COLUMN IF NOT EXISTS last_test_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS last_wrong_word_ids UUID[] DEFAULT '{}';
